yugabyte/src/yugabyte/core.clj, yugabyte/src/yugabyte/runner.clj, yugabyte/src/yugabyte/single_row_inserts.clj
https://github.com/YugaByte/yugabyte-db/issues/116
=> #116: Test and validate single row inserts

yugabyte/project.clj, yugabyte/src/yugabyte/common.clj, yugabyte/src/yugabyte/core.clj, yugabyte/src/yugabyte/nemesis.clj, yugabyte/src/yugabyte/runner.clj, yugabyte/src/yugabyte/single_row_inserts.clj
https://github.com/YugaByte/yugabyte-db/issues/130
=> #130: Implemented single fault nemeses

yugabyte/project.clj, yugabyte/setup-jepsen.sh, yugabyte/src/yugabyte/nemesis.clj, yugabyte/src/yugabyte/single_row_inserts.clj
https://github.com/YugaByte/yugabyte-db/issues/132
=> #132: Random partition nemesis

yugabyte/src/yugabyte/nemesis.clj, yugabyte/src/yugabyte/single_row_inserts.clj
https://github.com/YugaByte/yugabyte-db/issues/133
=> #133: Majority ring partitions

jepsen/src/jepsen/nemesis/time.clj, jepsen/src/jepsen/os.clj, jepsen/src/jepsen/os/centos.clj, jepsen/src/jepsen/os/debian.clj, yugabyte/project.clj, yugabyte/src/yugabyte/core.clj, yugabyte/src/yugabyte/nemesis.clj, yugabyte/src/yugabyte/single_key_acid.clj, yugabyte/src/yugabyte/single_row_inserts.clj
https://github.com/YugaByte/yugabyte-db/issues/168
=> #168: Jepsen failure scenarios - implement clock skew

yugabyte/src/yugabyte/core.clj, yugabyte/src/yugabyte/multi_key_acid.clj, yugabyte/src/yugabyte/runner.clj, yugabyte/src/yugabyte/single_key_acid.clj, yugabyte/src/yugabyte/single_row_inserts.clj
https://github.com/YugaByte/yugabyte-db/issues/169
=> #169: Multi-key ACID test

yugabyte/src/yugabyte/multi_key_acid.clj, yugabyte/src/yugabyte/single_key_acid.clj, yugabyte/src/yugabyte/single_row_inserts.clj
https://github.com/YugaByte/yugabyte-db/issues/315
=> #315: ENG-3341: Fixed error handling

yugabyte/src/yugabyte/multi_key_acid.clj, yugabyte/src/yugabyte/single_key_acid.clj, yugabyte/src/yugabyte/single_row_inserts.clj
https://github.com/YugaByte/yugabyte-db/issues/399
=> #399: ENG-3496: Duplicate writes due to retries in Cassandra driver

yugabyte/src/yugabyte/core.clj, yugabyte/src/yugabyte/nemesis.clj
https://github.com/YugaByte/yugabyte-db/issues/400
=> #400: ENG-3657: Jepsen testing: need to pass --max_clock_skew_usec flag to tserver

jepsen/project.clj, jepsen/src/jepsen/checker.clj, yugabyte/run-jepsen.py, yugabyte/src/yugabyte/counter.clj, yugabyte/src/yugabyte/runner.clj
https://github.com/YugaByte/yugabyte-db/issues/733
Used https://github.com/riptano/jepsen/blob/cassandra/cassandra/src/cassandra/counter.clj as a base for counter test.
Taken `checker.counter` changes from https://github.com/riptano/jepsen/blob/master/jepsen/src/jepsen/checker.clj#L182 and updated to be compatible with Jepsen framework 0.3.3.
=> #733: ENG-3337: Add Jepsen counter test

yugabyte/run-jepsen.py, yugabyte/src/yugabyte/bank.clj, yugabyte/src/yugabyte/runner.clj
https://github.com/YugaByte/yugabyte-db/issues/758
=> #758: ENG-3759: Added bank account test

yugabyte/README.md
Preview: https://github.com/YugaByte/jepsen/blob/update-readme/yugabyte/README.md
=> ENG-3918: Update YugaByte Jepsen tests readme

yugabyte/src/yugabyte/core.clj, yugabyte/src/yugabyte/counter.clj, yugabyte/src/yugabyte/multi_key_acid.clj, yugabyte/src/yugabyte/nemesis.clj, yugabyte/src/yugabyte/single_key_acid.clj, yugabyte/src/yugabyte/single_row_inserts.clj
https://github.com/YugaByte/yugabyte-db/issues/775
- Added cluster healing
- Renamed tests to avoid spaces in corresponding test results directories
- Don't download symlinks to cluster logs
=> #775: ENG-4534: Add cluster healing

yugabyte/src/yugabyte/bank.clj, yugabyte/src/yugabyte/multi_key_acid.clj, yugabyte/src/yugabyte/single_key_acid.clj
https://github.com/YugaByte/yugabyte-db/issues/789
=> #789: ENG-4567: Removed unnecessary wait-for-recovery calls

yugabyte/src/yugabyte/single_row_inserts.clj
https://github.com/YugaByte/yugabyte-db/issues/819
=> #819: Fixed fails calculation for single-row-inserts test

yugabyte/src/yugabyte/client.clj
https://github.com/YugaByte/yugabyte-db/issues/846
=> #846: Jepsen: Treat NoHostAvailableException with a list of hosts tried as info/unknown instead of fail

yugabyte/src/yugabyte/client.clj
https://github.com/YugaByte/yugabyte-db/issues/847
=> #847: Fixed retrying in client/await-setup

yugabyte/project.clj
https://github.com/YugaByte/yugabyte-db/issues/1147
=> #1147: Updated cassaforte dependency

yugabyte/src/yugabyte/client.clj
https://github.com/YugaByte/yugabyte-db/issues/1105
=> #1105: Jepsen: update CQL client to reflect changes in error message for already existing index

yugabyte/run-jepsen.py
https://github.com/YugaByte/yugabyte-db/issues/1161
=> #1161: Updated run-jepsen.py

yugabyte/src/yugabyte/auto.clj
Resolves https://github.com/YugaByte/yugabyte-db/issues/1490
=> [#1490] Removed unnecessary excessive --v=3 logs

yugabyte/src/yugabyte/bank.clj, yugabyte/src/yugabyte/core.clj, yugabyte/src/yugabyte/ycql/client.clj, yugabyte/src/yugabyte/ysql/bank.clj, yugabyte/src/yugabyte/ysql/client.clj, yugabyte/src/yugabyte/ysql/counter.clj
https://github.com/YugaByte/yugabyte-db/issues/938, https://github.com/YugaByte/yugabyte-db/issues/1569
* Added client for Jepsen `bank` test
* Enabled `negative-balances?` for now since it makes current issue https://github.com/YugaByte/yugabyte-db/issues/1553 more evident
* Refactored existing YSQL framework to add a `defclient` macro
* (Minor) Replaced tabs with spaces in YCQL client code
=> [YSQL] Bank test, client macro (#1569)

yugabyte/src/yugabyte/auto.clj, yugabyte/src/yugabyte/core.clj, yugabyte/src/yugabyte/runner.clj
Resolves YugaByte/yugabyte-db#1650
=> Removed outdated code related to enterprise version of YB (YugaByte/yugabyte-db#1650) 

yugabyte/src/yugabyte/ysql/bank.clj, yugabyte/src/yugabyte/ysql/client.clj
Resolves YugaByte/yugabyte-db#1714
=> SQL connections made serializable by default (YugaByte/yugabyte-db#1714)

yugabyte/src/yugabyte/auto.clj, yugabyte/src/yugabyte/bank.clj, yugabyte/src/yugabyte/counter.clj, yugabyte/src/yugabyte/generator.clj, yugabyte/src/yugabyte/long_fork.clj, yugabyte/src/yugabyte/multi_key_acid.clj, yugabyte/src/yugabyte/set.clj, yugabyte/src/yugabyte/single_key_acid.clj, yugabyte/src/yugabyte/utils.clj, yugabyte/src/yugabyte/ysql/bank.clj, yugabyte/src/yugabyte/ysql/client.clj, yugabyte/src/yugabyte/ysql/counter.clj, yugabyte/src/yugabyte/ysql/long_fork.clj, yugabyte/src/yugabyte/ysql/multi_key_acid.clj, yugabyte/src/yugabyte/ysql/set.clj, yugabyte/src/yugabyte/ysql/single_key_acid.clj
Resolves https://github.com/YugaByte/yugabyte-db/issues/1689, see tickets description.
=> Add metadata to Jepsen operations history (YugaByte/yugabyte-db#1689)

yugabyte/src/yugabyte/generator.clj, yugabyte/src/yugabyte/ysql/client.clj
Resolves https://github.com/YugaByte/yugabyte-db/issues/1722
Disabled retries for YSQL test operations, done some minor cleanup as well
=> [YSQL] Disable retries for test operations (YugaByte/yugabyte-db#1722)
